name: Playwright Tests
on:
  push:
    branches: [ master ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Use Node.js
                uses: actions/setup-node@v4
            -   name: Install dependencies
                run: |
                    echo "📥 Installing project dependencies..."
                    npm ci
                    echo "✅ Dependencies installed successfully!"
            
            -   name: Print Workspace Contents
                run: |
                    echo "📂 Current workspace contents:"
                    ls -la
            