name: Playwright Tests
on:
  push:
    branches: [ master ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
                with:
                    submodules: recursive
            -   name: Debug Submodule
                run:  git submodule status
                
            -   name: Use Node.js
                uses: actions/setup-node@v4
                
            -   name: Install dependencies
                run: |
                    npm ci
                    echo "✅ Dependencies installed successfully!"
                    npx playwright install --with-deps
                    echo "✅ Browsers installed successfully!"
            
            -   name: Run Playwright tests
                env:
                    PW_USERNAME: ${{ secrets.PW_USERNAME }}
                    PW_PASSWORD: ${{ secrets.PW_PASSWORD }}
                run: npx playwright test

            -   name: Upload test results
                uses: actions/upload-artifact@v4
                if: always()
                with:
                    name: playwright-report
                    path: playwright-report
                    retention-days: 30 
            
